name: flutter_example_riverpod
description: A Flutter Riverpod Example.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13

dev_dependencies:
  all_lint_rules_community: ^0.0.25
  build_runner: ^2.3.3
  custom_lint: ^0.2.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  riverpod_lint: ^1.0.1


flutter:
  uses-material-design: true